# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/41a6d091-cca7-40f1-bbea-cf9a4a23ec1b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/212ffe12-1e30-473c-a943-95e6c306e60d";
      fsType = "ext2";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/829d0bab-bb55-49c9-8b44-e5c6c66ae13c"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
